public enum DatatypeOut {
	LEFT_FRONT_MOTOR(0x00),
	RIGHT_FRONT_MOTOR(0x01),
	LEFT_BACK_MOTOR(0x02),
	RIGHT_BACK_MOTOR(0x03),
	LEFT_FRONT_PID_PROPORTIONAL(0x04),
	LEFT_FRONT_PID_INTEGRAL(0x05),
	LEFT_FRONT_PID_DERIVATIVE(0x06),
	LEFT_FRONT_PID_FEED_FORWARD(0x07),
	LEFT_FRONT_PID_I_ZONE(0x08),
	RIGHT_FRONT_PID_PROPORTIONAL(0x09),
	RIGHT_FRONT_PID_INTEGRAL(0x01),
	RIGHT_FRONT_PID_DERIVATIVE(0x0b),
	RIGHT_FRONT_PID_FEED_FORWARD(0x0c),
	RIGHT_FRONT_PID_I_ZONE(0x0d),
	LEFT_BACK_PID_PROPORTIONAL(0x0e),
	LEFT_BACK_PID_INTEGRAL(0x0f),
	LEFT_BACK_PID_DERIVATIVE(0x10),
	LEFT_BACK_PID_FEED_FORWARD(0x11),
	LEFT_BACK_PID_I_ZONE(0x12),
	RIGHT_BACK_PID_PROPORTIONAL(0x13),
	RIGHT_BACK_PID_INTEGRAL(0x14),
	RIGHT_BACK_PID_DERIVATIVE(0x15),
	RIGHT_BACK_PID_FEED_FORWARD(0x16),
	RIGHT_BACK_PID_I_ZONE(0x17),
	// RESERVED_LEFT_ULTRASONIC(0x18),
	// RESERVED_RIGHT_ULTRASONIC(0x19),
	// RESERVED_FRONT_ULTRASONIC(0x1a),
	// RESERVED_BACK_ULTRASONIC(0x1b),
	DIGITAL_OUTPUT_1(0x1c),
	DIGITAL_OUTPUT_2(0x1d),
	DIGITAL_OUTPUT_3(0x1e),
	DIGITAL_OUTPUT_4(0x1f),
	DIGITAL_OUTPUT_5(0x20),
	DIGITAL_OUTPUT_6(0x21),
	DIGITAL_OUTPUT_7(0x22),
	DIGITAL_OUTPUT_8(0x23),
	DIGITAL_OUTPUT_9(0x24),
	DIGITAL_OUTPUT_10(0x25),

	READY(0xfe),
	ERROR(0xff);

	private final int value;

	DatatypeOut(final int newValue) {
		value = newValue;
	}

	public int getValue() { return value; }
}
